version: "3.10"

services:
  web:
    env_file:
      - docker.env
    build: .
    command: gunicorn --workers=3 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker costsmap.main:app
    volumes:
      - ./costsmap:/code/costsmap
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=costsmap
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
