[tool.poetry]
name = "costsmap"
version = "0.1.0"
description = ""
authors = ["artemowkin <artyom.groshev2017@gmail.com>"]
readme = "README.md"
packages = [
    { include = 'costsmap' }
]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.88.0"
uvicorn = "^0.20.0"
pydantic = {extras = ["dotendv"], version = "^1.10.2"}
databases = "^0.6.2"
SQLAlchemy = "^1.4.41"
asyncpg = "^0.27.0"
passlib = "^1.7.4"
python-dotenv = "^0.21.0"
psycopg2-binary = "^2.9.5"
python-jose = "^3.3.0"
pytz = "^2022.6"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dev = "costsmap.main:main"
