# Generated by Django 3.2.4 on 2021-06-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_cost_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ('-date', '-pub_datetime'), 'verbose_name': 'cost', 'verbose_name_plural': 'costs'},
        ),
    ]
